# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-29 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200229_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 8, 3, 55, 431857, tzinfo=utc)),
        ),
    ]
