# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-01 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200229_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 4, 25, 0, 795184, tzinfo=utc)),
        ),
    ]
